[package]
name = "coitrees"
version = "0.1.0"
authors = ["Daniel C. Jones <dcjones@cs.washington.edu>"]
edition = "2018"

[profile.release]
debug = true

[dependencies]
fnv = "1.0.3"
libc = "0.2"
clap = "3.0.0-beta.1"
